# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "client id"
name = "learn1"
handle = "learn1-1"
application_url = "URL"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "themsimo1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "URL/auth/callback",
  "URL/auth/shopify/callback",
  "URL/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
